[package]
name = "pyef"
version = "0.1.0"
authors = ["Gu Junhua <jhgu@nao.cas.cn>"]


[lib]
name = "pyef"
crate-type = ["cdylib"]


[dependencies]
rayon = "1.0.2"

[dependencies.pyo3]
path="../pyo3"
features = ["extension-module"]

[dependencies.gp_daq]
path="../gp_daq"
