[dependencies]
rayon = '1.3.1'

[dependencies.gp_daq]
path = '../gp_daq'

[dependencies.pyo3]
features = ['extension-module']
version = '0.11.1'

[lib]
crate-type = ['cdylib']
name = 'native'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'pyef'
version = '0.1.0'
